### PR TITLE
Implement blur effect

### PR DESCRIPTION
**Pull request by chregu**
This patch (currently only) implements the blur effect. Maybe useful for some. If anyone  likes to add more effects, I'd be happy to integrate them here, before it gets eventually merged.

### CODE REVIEW

**Comment by leofeyer** [comment]
I like the idea and it could help solving https://github.com/contao/core-bundle/issues/1202#issuecomment-347317347 – although we might need to implement the other methods, too.

**Comment by ausi** [comment]
Looks great, thank you @chregu!

I think we should add some checks here:

1. If the `filter` attribute is already set, we should append or prepend the blur filter.
2. IDs need to be unique, so we should check that the ID of the filter doesn’t exist already.
3. SVGs can be inlined in HTML, so we should try to use a very unique id (maybe random or some hash).

**Comment by chregu** [comment]
Totally agree with those 3 points. It was sufficient enough for our needs, but should definitely be extended for common useage

**Comment by ausi** [comment]
I created a followup pull request: #10

@chregu It would be great if you could take a look if this still generates the desired results for your use case.

**Comment by chregu** [comment]
@ausi Cool, thanks a lot for the additional work you put into. Works fine on our project with your code.

**Comment by Toflar** [comment]
@chregu, is that for rokka.io? 😄

**Comment by chregu** [comment]
@Toflar Sure thing ;)

**Comment by ausi** [comment]
Merged in f126fcaf5c01cd625b6e0fe1b740081cbdbc5f62 and ba853e24259f7e4444faf3dbad02de9f113ee13e.

Thank you @chregu!

**Comment by chregu** [comment]
Thank you all for making it better 💛

**Pull request closed without merging**
